repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.1'
    hooks:
      - id: ruff
        args: [ "--fix" ]
  - repo: https://github.com/psf/black
    rev: "23.10.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace